//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookStory
    {
        public int id { get; set; }
        public string title { get; set; }
        public string pdf { get; set; }
        public string InteractiveFile { get; set; }
        public Nullable<int> bookId { get; set; }
        public string thumb { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
