//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.BookSlides = new HashSet<BookSlide>();
            this.ItemsCategories = new HashSet<ItemsCategory>();
            this.ItemsLevels = new HashSet<ItemsLevel>();
            this.QuestionsCategories = new HashSet<QuestionsCategory>();
            this.SchoolBooks = new HashSet<SchoolBook>();
            this.StudentLibraries = new HashSet<StudentLibrary>();
            this.StudentScores = new HashSet<StudentScore>();
            this.BookInteractiveChapters = new HashSet<BookInteractiveChapter>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string artitle { get; set; }
        public string pdf { get; set; }
        public string text { get; set; }
        public string artext { get; set; }
        public string thumb { get; set; }
        public string video { get; set; }
        public Nullable<bool> isAvailable { get; set; }
        public string background { get; set; }
        public string SignLanguageVideo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookSlide> BookSlides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsCategory> ItemsCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsLevel> ItemsLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionsCategory> QuestionsCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolBook> SchoolBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentLibrary> StudentLibraries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentScore> StudentScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookInteractiveChapter> BookInteractiveChapters { get; set; }
    }
}
