//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookGame()
        {
            this.SchoolGames = new HashSet<SchoolGame>();
        }
    
        public int id { get; set; }
        public Nullable<int> levelId { get; set; }
        public string Folder { get; set; }
        public string Thumb { get; set; }
        public Nullable<int> categoryId { get; set; }
    
        public virtual Level Level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolGame> SchoolGames { get; set; }
        public virtual Category Category { get; set; }
    }
}
