//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_user
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> groupId { get; set; }
        public Nullable<System.DateTime> date_login { get; set; }
        public Nullable<bool> isOnline { get; set; }
        public string img { get; set; }
        public Nullable<int> status { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string email { get; set; }
    
        public virtual cms_groups cms_groups { get; set; }
    }
}
