//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int id { get; set; }
        public string AboutUs { get; set; }
        public string Email { get; set; }
        public string AddressLine { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public string Logo { get; set; }
        public string SmtpServer { get; set; }
        public string SmtpPort { get; set; }
        public Nullable<bool> IsSSL { get; set; }
        public string SystemEmail { get; set; }
        public string SystemEmailPassword { get; set; }
        public string InfoEmail { get; set; }
        public string keywords { get; set; }
        public string Description { get; set; }
        public string SmartLearningVideo { get; set; }
    }
}
