//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionsAnswer
    {
        public int id { get; set; }
        public Nullable<int> questionId { get; set; }
        public string audio { get; set; }
        public string x { get; set; }
        public string y { get; set; }
        public string width { get; set; }
        public string text { get; set; }
        public string type { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
