//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.QuestionsAnswers = new HashSet<QuestionsAnswer>();
        }
    
        public int id { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string title { get; set; }
        public string type { get; set; }
        public string audio { get; set; }
        public string correctAnswer { get; set; }
        public string AnswersLayout { get; set; }
    
        public virtual QuestionsCategory QuestionsCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionsAnswer> QuestionsAnswers { get; set; }
    }
}
